### ISSUE TITLE
Bad formatting in App Blades docs

### ISSUE THREAD

**Issue by juliusl** [Azure/portaldocs#11]
https://github.com/Azure/portaldocs/blob/c08087831fe2741101ce792572f2e92a399b4a99/portal-sdk/templates/portalfx-blades-appblades.md

Bits of json scattered about that look like they refer to files.

**Comment by amitgetgit** [comment]
We have addressed all the issues related to scattered json and broken link. Please take a look at the latest docs at: https://github.com/Azure/portaldocs/blob/master/portal-sdk/generated/portalfx-blades-appblades.md
