### ISSUE TITLE
Assigning certificate to Linux Virtual Machine

### ISSUE THREAD

**Issue by WiseMack** [Azure/portaldocs#182]
Assigning to Virtual Machine
An issued App Service certificate may be used on any App Service Web App. Follow the steps below to assign the certificate to an App Service App.

- Get the Key Vault information for your SSL certificate resource under certificate configuration.

Where is the Key Vault information stored?
- Prepare and Configure the virtual machine to add the Certificate.

How exactly do you configure the virtual machine, What are the steps?

An App Service Certificate can be used on multiple Azure Virtual Machines. Learn more

Please add details!

Note the "Learn more" link does not have more information.
https://blogs.msdn.microsoft.com/appserviceteam/2017/10/26/configure-app-service-certificate-to-azure-virtual-machine/

Note2:
In https://blogs.msdn.microsoft.com/appserviceteam/2017/10/26/configure-app-service-certificate-to-azure-virtual-machine/ there is a statement:

"When you run the previous script, the output includes the secret URI. Make a note of this URI. You have to reference it in the Push certificate to Windows Resource Manager template. Download the vm-push-certificate-windows template folder to your development computer. This folder contains the azuredeploy.json and azuredeploy.parameters.json files, which you will need in the next steps."

This works for windows vms only, not on linux vms

Note3:
Neither of https://github.com/Azure/AzureStack-QuickStart-Templates/tree/master/101-vm-windows-create-passwordfromkv nor https://github.com/Azure/AzureStack-QuickStart-Templates/tree/master/201-vm-windows-pushcertificate have a space for a ssh password, only regular passwords

**Comment by WiseMack** [comment]
This is a request to add information to the azure portal in 
App Service certificate -->Certificate Configuration-->Step 3 Assign
the App Service version has several steps

Assigning to App Service App
An issued App Service certificate may be used on any App Service Web App. Follow the steps below to assign the certificate to an App Service App.
- Click the App Service option on the left side of the page.
- Click the name of your app to which you want to assign this certificate.
- In the Settings, Click Custom domains and SSL.
- In the certificates section, click Import Certificate and select the Certificate that you just purchased.
- In the ssl bindings section of the SSL Settings tab, use the dropdowns to select the domain name to secure with SSL, and the certificate to use.
- Click Save to save the changes and enable SSL.

An App Service Certificate can be used on multiple App Service Apps.

But the Virtual Machine version does not

**Comment by rowong** [comment]
Hi,

I think you raised this issue in the wrong github repository.  Based on your comment in the "Note3" section, I'm guessing you want to file your issue in the https://github.com/Azure/AzureStack-QuickStart-Templates repo
