### ISSUE TITLE
Open Sourcing Azure Portal SDK

### ISSUE THREAD

**Issue by grahamehorner** [Azure/portaldocs#25]
please consider open sourcing the Azure Portal SDK, so that on-premise deployment of Azure Stack may be used/extended with custom in-house extensions and/or used to develop/test extensions before publishing to the public Azure platform.

**Comment by amitgetgit** [comment]
Thanks for the feedback.  We are continuously making improvements in the SDK with long term goal to making SDK public. We do not have an ETA this so far. We will update the comments once we have a plan.
