### ISSUE TITLE
Onboarding - broken links

### ISSUE THREAD

**Issue by grahamehorner** [Azure/portaldocs#26]
https://github.com/Azure/portaldocs/blob/master/portal-sdk/generated/portalfx-onboarding.md#portal-extension

I would very much like to join the program, with a view to creating a Azure extension/application for a project, however the links are broken?

**Comment by amitgetgit** [comment]
Thanks a lot for helping us identify issues with our document. We have fixed the links and added tests to ensure we do not introduce any more broken links. If you see any other issues please let us know. Thanks,
Amit
