### ISSUE TITLE
Links are broken from Performance Checklist page

### ISSUE THREAD

**Issue by rgovardhms** [Azure/portaldocs#6]
The links are broken from the performance checklist page - https://github.com/Azure/portaldocs/blob/master/portal-sdk/templates/portalfx-performance-checklist.md

Can you please fix this?

**Comment by amitgetgit** [comment]
The links have been fixed and we have published the latest docs at: https://github.com/Azure/portaldocs/blob/master/portal-sdk/generated/portalfx-performance-checklist.md
