### ISSUE TITLE
Links to msi's missing from downloads.md

### ISSUE THREAD

**Issue by csteez** [Azure/portaldocs#93]
https://github.com/Azure/portaldocs/blob/master/portal-sdk/generated/downloads.md

This no longer has links to the downloads as of 2 days ago. 
https://github.com/Azure/portaldocs/commit/a25bb33fe0683e1f13a88d914badcf36efce1d2c#diff-9cdcdb85838ded3230ad9e0d7f5de522
This commit has the removal. Was this intentional?

**Comment by nickharris** [comment]
occasionally an SDK will be revoked. when the links are not present it means the sdk has been revoked.
